const GAME_FIELD_WIDTH = 13;
const GAME_FIELD_HEIGHT = 18;
const BLOCK_SIZE = 32;
const SPAWN_POINT_X = 5;
const SPAWN_POINT_Y = -3;

export { GAME_FIELD_WIDTH, GAME_FIELD_HEIGHT, BLOCK_SIZE, SPAWN_POINT_X, SPAWN_POINT_Y };
